language: ruby
rvm:
- 2.4.5
before_install:
- gem update --system
- gem install bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: u/mSZD/cZ7LbtvfP2C8iWG+PTPxtM6WQ3zECk0stzgs1stJFYhlf+GQcSigtiEx+dlMax16LIsSr2RP5NR8+wydohxPbHvfzPwnAdP0QPMP/82wPcHv8uZjL1Uu+GCjXcnAMWxRy/pekHgY/7ohUMeXox/I8ynr3dpTnZpVp9bl9OOVqso8NEp7vNWOTih1TRkFV2i0N/OHEU8IloRG28bgiHJwRd4WWK6CPoFwFdB7ABeXICpen3B+ieZttASGcLRvT8Bp/ZI+TxqxWoNA/4pMmt0f3OvI/t8zWTyKZyIl3BQOw1Xe03G2eYnofTsLD5NkRvQ4LGTV+48IQpQdjUUWVtiDafX/TCQS7mvDcrg2km3BZijIzaUnoRtjgQrrQoSIALFhLkkI9+hY70yqSupsz+XkFnDVqxlchnkOGmZDvTIhs+jbFPObQXaWRfrVnetwkHdvoqmyEXPjFmZZt+SADLyB3vPv8BsKabBhNZ/QV14yFJTsPi3xP9ZO4UPatiDNH12rBGFZo5MUJs05PSezlD0sVEcM+89ZCJMi6sI8uGiJOgDMIqXp/s3/LRXHn+w7msEJrPfI1tQXUbeozCRxIrT8HBsiNfDC1xcxufaRMxmv1IUplCk3VIueKEKOUL9PBZ/m3ayyZeFGVbmucZ9Xu/0ciFFcZUthY4pqdESs=
  app: vast-ridge-78927
