language: ruby
rvm:
- 2.4.5
before_install:
- gem update --system
- gem install bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: N3Qr163blqcnxzgbeSgWPukzECGxRAqzsy7Lei1Gy0qxHNG4+9aaknRvP35KqYewOujVh927kSIBvLWiK4zeeDBdYEQ5Ly08uoCJ8+v+cBj4AstTTAAoVVpGr87hDW9AKhcvz3KM5Xzaz/UJAw9hPPJDze5X040Kx454JPLO8pS0yGd0gI7AGJMavB6J9EdMpyK/bF/R2GBCXM9Dsq1KPvOu2OU8O3HdxZxIo7r8ibWMjeGlDiE8nDt96WT8PdOPfNUWN7w/Y6xqYc0Zf+Oo7LSbGwBave315P4EKf0K/tX1S/HygivN+AgCz4fXcpBOXOuEH8Q3VL02mpTkL6I5b1vI8Iue2Rl7veU7wDR98C3YnmM2OJjzWzQ+KAdssYPt2AEF70puxprr+iW3odNm+25Td8KbiUQfCOfpl90fBvHIt4LJaqKP1ZBnwrjZ153GXpg30jGUCZIFDqhaqKKH55V0WeUuM1I0FwbJqvHG+i+4+akFzIsASyeMltJgvON75uXHanYXP1Gez1EppCQ0yQNasFmDBONi0qIStj0KUYzwwWRXhtyhTDnlgI7kGSs6n/wCyxCmUsIruuiR9zel7hUBIfUJ8EZVgbFPgUoGssslJbCJ0lcDIRjTHcqdUKwyRB8ih5SzCkKDvTKRaXeHJ+tY0fWCIImKRUJjxaK3qVQ=
  app: vast-ridge-78927
  on:
    repo: le3ah/my_sage_says
